[package]
name = "eng_tester"
version = "0.1.0"
authors = ["Alexander Pateenok <pateenoc@gmail.com>"]
description = "Knowledge testing app from org-mode tables"
license = "GPL-3.0"

[dependencies]
rand = "0.4.2"
structopt = "0.2.7"

[dependencies.cursive]
version = "0.8.1"
default-features = false
features = ["pancurses-backend"]
