[package]
name = "eng_tester"
version = "0.1.0"
authors = ["Alexander Pateenok <pateenoc@gmail.com>"]
description = "Knowledge testing app from org-mode tables"
license = "GPL-3.0"

[dependencies]
rand = "0.4.2"
cursive = "0.8.1"
